//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 09:01:52 PM CEST 
//


package web.poslovna.model.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Analitika_izvoda" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="duznik" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="svrha" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="poverliac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="datumValute" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="datumPrijema" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="racunDuznika" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="modelZaduzenja" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="pozivNaBrojZaduzenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="racunPoverioca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="modelOdobrenja" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="idVrstaPlacanja" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="nazivPlacanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="idNaselje" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="nazivNaselja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="idValute" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="idRacunaPoverioca" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="idRacunaDuznika" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="valuta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="hitno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tipGreske" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="iznos" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="pozivNaBrojOdobrenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "analitikaIzvoda"
})
@XmlRootElement(name = "ListaAnalitika")
public class ListaAnalitika {

    @XmlElement(name = "Analitika_izvoda")
    protected List<ListaAnalitika.AnalitikaIzvoda> analitikaIzvoda;

    /**
     * Gets the value of the analitikaIzvoda property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the analitikaIzvoda property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnalitikaIzvoda().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListaAnalitika.AnalitikaIzvoda }
     * 
     * 
     */
    public List<ListaAnalitika.AnalitikaIzvoda> getAnalitikaIzvoda() {
        if (analitikaIzvoda == null) {
            analitikaIzvoda = new ArrayList<ListaAnalitika.AnalitikaIzvoda>();
        }
        return this.analitikaIzvoda;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="duznik" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="svrha" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="poverliac" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="datumValute" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="datumPrijema" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="racunDuznika" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="modelZaduzenja" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="pozivNaBrojZaduzenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="racunPoverioca" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="modelOdobrenja" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="idVrstaPlacanja" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="nazivPlacanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="idNaselje" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="nazivNaselja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="idValute" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="idRacunaPoverioca" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="idRacunaDuznika" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="valuta" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="hitno" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tipGreske" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="iznos" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="pozivNaBrojOdobrenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "duznik",
        "svrha",
        "poverliac",
        "datumValute",
        "datumPrijema",
        "racunDuznika",
        "modelZaduzenja",
        "pozivNaBrojZaduzenja",
        "racunPoverioca",
        "modelOdobrenja",
        "idVrstaPlacanja",
        "nazivPlacanja",
        "idNaselje",
        "nazivNaselja",
        "idValute",
        "idRacunaPoverioca",
        "idRacunaDuznika",
        "valuta",
        "hitno",
        "status",
        "tipGreske",
        "iznos",
        "pozivNaBrojOdobrenja",
        "idIzvoda"
    })
    public static class AnalitikaIzvoda {

        protected int id;
        @XmlElement(required = true)
        protected String duznik;
        @XmlElement(required = true)
        protected String svrha;
        @XmlElement(required = true)
        protected String poverliac;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumValute;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumPrijema;
        @XmlElement(required = true)
        protected String racunDuznika;
        protected double modelZaduzenja;
        @XmlElement(required = true)
        protected String pozivNaBrojZaduzenja;
        @XmlElement(required = true)
        protected String racunPoverioca;
        protected double modelOdobrenja;
        protected double idVrstaPlacanja;
        @XmlElement(required = true)
        protected String nazivPlacanja;
        protected int idNaselje;
        @XmlElement(required = true)
        protected String nazivNaselja;
        @XmlElement(required = true)
        protected BigInteger idValute;
        protected int idRacunaPoverioca;
        protected int idRacunaDuznika;
        @XmlElement(required = true)
        protected String valuta;
        protected boolean hitno;
        @XmlElement(required = true)
        protected String status;
        protected double tipGreske;
        protected double iznos;
        @XmlElement(required = true)
        protected String pozivNaBrojOdobrenja;
        @XmlElement(required = true)
        private int idIzvoda;

        
        
        
        public AnalitikaIzvoda(int id, String duznik, String svrha,
				String poverliac, XMLGregorianCalendar datumValute,
				XMLGregorianCalendar datumPrijema, String racunDuznika,
				double modelZaduzenja, String pozivNaBrojZaduzenja,
				String racunPoverioca, double modelOdobrenja,
				double idVrstaPlacanja, String nazivPlacanja, int idNaselje,
				String nazivNaselja, BigInteger idValute, String valuta,
				boolean hitno, String status, double tipGreske, double iznos,
				String pozivNaBrojOdobrenja, int idIzvoda) {
			super();
			this.id = id;
			this.duznik = duznik;
			this.svrha = svrha;
			this.poverliac = poverliac;
			this.datumValute = datumValute;
			this.datumPrijema = datumPrijema;
			this.racunDuznika = racunDuznika;
			this.modelZaduzenja = modelZaduzenja;
			this.pozivNaBrojZaduzenja = pozivNaBrojZaduzenja;
			this.racunPoverioca = racunPoverioca;
			this.modelOdobrenja = modelOdobrenja;
			this.idVrstaPlacanja = idVrstaPlacanja;
			this.nazivPlacanja = nazivPlacanja;
			this.idNaselje = idNaselje;
			this.nazivNaselja = nazivNaselja;
			this.idValute = idValute;
			this.valuta = valuta;
			this.hitno = hitno;
			this.status = status;
			this.tipGreske = tipGreske;
			this.iznos = iznos;
			this.pozivNaBrojOdobrenja = pozivNaBrojOdobrenja;
			this.idIzvoda = idIzvoda;
		}

		public AnalitikaIzvoda() {
			// TODO Auto-generated constructor stub
		}

		
		
		public int getIdIzvoda() {
			return idIzvoda;
		}

		public void setIdIzvoda(int idIzvoda) {
			this.idIzvoda = idIzvoda;
		}

		/**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the duznik property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDuznik() {
            return duznik;
        }

        /**
         * Sets the value of the duznik property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDuznik(String value) {
            this.duznik = value;
        }

        /**
         * Gets the value of the svrha property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSvrha() {
            return svrha;
        }

        /**
         * Sets the value of the svrha property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSvrha(String value) {
            this.svrha = value;
        }

        /**
         * Gets the value of the poverliac property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoverliac() {
            return poverliac;
        }

        /**
         * Sets the value of the poverliac property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoverliac(String value) {
            this.poverliac = value;
        }

        /**
         * Gets the value of the datumValute property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumValute() {
            return datumValute;
        }

        /**
         * Sets the value of the datumValute property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumValute(XMLGregorianCalendar value) {
            this.datumValute = value;
        }

        /**
         * Gets the value of the datumPrijema property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPrijema() {
            return datumPrijema;
        }

        /**
         * Sets the value of the datumPrijema property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPrijema(XMLGregorianCalendar value) {
            this.datumPrijema = value;
        }

        /**
         * Gets the value of the racunDuznika property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRacunDuznika() {
            return racunDuznika;
        }

        /**
         * Sets the value of the racunDuznika property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRacunDuznika(String value) {
            this.racunDuznika = value;
        }

        /**
         * Gets the value of the modelZaduzenja property.
         * 
         */
        public double getModelZaduzenja() {
            return modelZaduzenja;
        }

        /**
         * Sets the value of the modelZaduzenja property.
         * 
         */
        public void setModelZaduzenja(double value) {
            this.modelZaduzenja = value;
        }

        /**
         * Gets the value of the pozivNaBrojZaduzenja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPozivNaBrojZaduzenja() {
            return pozivNaBrojZaduzenja;
        }

        /**
         * Sets the value of the pozivNaBrojZaduzenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPozivNaBrojZaduzenja(String value) {
            this.pozivNaBrojZaduzenja = value;
        }

        /**
         * Gets the value of the racunPoverioca property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRacunPoverioca() {
            return racunPoverioca;
        }

        /**
         * Sets the value of the racunPoverioca property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRacunPoverioca(String value) {
            this.racunPoverioca = value;
        }

        /**
         * Gets the value of the modelOdobrenja property.
         * 
         */
        public double getModelOdobrenja() {
            return modelOdobrenja;
        }

        /**
         * Sets the value of the modelOdobrenja property.
         * 
         */
        public void setModelOdobrenja(double value) {
            this.modelOdobrenja = value;
        }

        /**
         * Gets the value of the idVrstaPlacanja property.
         * 
         */
        public double getIdVrstaPlacanja() {
            return idVrstaPlacanja;
        }

        /**
         * Sets the value of the idVrstaPlacanja property.
         * 
         */
        public void setIdVrstaPlacanja(double value) {
            this.idVrstaPlacanja = value;
        }

        /**
         * Gets the value of the nazivPlacanja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivPlacanja() {
            return nazivPlacanja;
        }

        /**
         * Sets the value of the nazivPlacanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivPlacanja(String value) {
            this.nazivPlacanja = value;
        }

        /**
         * Gets the value of the idNaselje property.
         * 
         */
        public int getIdNaselje() {
            return idNaselje;
        }

        /**
         * Sets the value of the idNaselje property.
         * 
         */
        public void setIdNaselje(int value) {
            this.idNaselje = value;
        }

        /**
         * Gets the value of the nazivNaselja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivNaselja() {
            return nazivNaselja;
        }

        /**
         * Sets the value of the nazivNaselja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivNaselja(String value) {
            this.nazivNaselja = value;
        }

        /**
         * Gets the value of the idValute property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIdValute() {
            return idValute;
        }

        /**
         * Sets the value of the idValute property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIdValute(BigInteger value) {
            this.idValute = value;
        }

        /**
         * Gets the value of the idRacunaPoverioca property.
         * 
         */
        public int getIdRacunaPoverioca() {
            return idRacunaPoverioca;
        }

        /**
         * Sets the value of the idRacunaPoverioca property.
         * 
         */
        public void setIdRacunaPoverioca(int value) {
            this.idRacunaPoverioca = value;
        }

        /**
         * Gets the value of the idRacunaDuznika property.
         * 
         */
        public int getIdRacunaDuznika() {
            return idRacunaDuznika;
        }

        /**
         * Sets the value of the idRacunaDuznika property.
         * 
         */
        public void setIdRacunaDuznika(int value) {
            this.idRacunaDuznika = value;
        }

        /**
         * Gets the value of the valuta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValuta() {
            return valuta;
        }

        /**
         * Sets the value of the valuta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValuta(String value) {
            this.valuta = value;
        }

        /**
         * Gets the value of the hitno property.
         * 
         */
        public boolean isHitno() {
            return hitno;
        }

        /**
         * Sets the value of the hitno property.
         * 
         */
        public void setHitno(boolean value) {
            this.hitno = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the tipGreske property.
         * 
         */
        public double getTipGreske() {
            return tipGreske;
        }

        /**
         * Sets the value of the tipGreske property.
         * 
         */
        public void setTipGreske(double value) {
            this.tipGreske = value;
        }

        /**
         * Gets the value of the iznos property.
         * 
         */
        public double getIznos() {
            return iznos;
        }

        /**
         * Sets the value of the iznos property.
         * 
         */
        public void setIznos(double value) {
            this.iznos = value;
        }

        /**
         * Gets the value of the pozivNaBrojOdobrenja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPozivNaBrojOdobrenja() {
            return pozivNaBrojOdobrenja;
        }

        /**
         * Sets the value of the pozivNaBrojOdobrenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPozivNaBrojOdobrenja(String value) {
            this.pozivNaBrojOdobrenja = value;
        }

    }

}
