//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 09:01:52 PM CEST 
//


package web.poslovna.model.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the web.poslovna.model.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: web.poslovna.model.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListaAnalitika }
     * 
     */
    public ListaAnalitika createListaAnalitika() {
        return new ListaAnalitika();
    }

    /**
     * Create an instance of {@link ListaAnalitika.AnalitikaIzvoda }
     * 
     */
    public ListaAnalitika.AnalitikaIzvoda createListaAnalitikaAnalitikaIzvoda() {
        return new ListaAnalitika.AnalitikaIzvoda();
    }

}
