//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 04:05:19 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.poslovna-banka.com/rtgs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package web.poslovna.model.xml;
