//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 04:05:19 PM CEST 
//


package web.poslovna.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Datum_valute" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="sifra">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Id_racun_banke_duznika" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="id_racun_banke_poverioca" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="naziv_banke_poverioca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="naziv_banke_duznika" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="racun_banke_poverioca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="racun_banke_duznika" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ukupno" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "datumValute",
    "datum",
    "sifra",
    "idRacunBankeDuznika",
    "idRacunBankePoverioca",
    "nazivBankePoverioca",
    "nazivBankeDuznika",
    "racunBankePoverioca",
    "racunBankeDuznika",
    "ukupno"
})
@XmlRootElement(name = "RTGS_Kliring")
public class RTGSKliring {

    protected int id;
    @XmlElement(name = "Datum_valute", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumValute;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;
    @XmlElement(required = true)
    protected String sifra;
    @XmlElement(name = "Id_racun_banke_duznika")
    protected int idRacunBankeDuznika;
    @XmlElement(name = "id_racun_banke_poverioca")
    protected int idRacunBankePoverioca;
    @XmlElement(name = "naziv_banke_poverioca", required = true)
    protected String nazivBankePoverioca;
    @XmlElement(name = "naziv_banke_duznika", required = true)
    protected String nazivBankeDuznika;
    @XmlElement(name = "racun_banke_poverioca", required = true)
    protected String racunBankePoverioca;
    @XmlElement(name = "racun_banke_duznika", required = true)
    protected String racunBankeDuznika;
    protected double ukupno;

    
    
    public RTGSKliring()
    {
    	
    }
    
    
    public RTGSKliring(int id, XMLGregorianCalendar datumValute,
			XMLGregorianCalendar datum, String sifra, int idRacunBankeDuznika,
			int idRacunBankePoverioca, String nazivBankePoverioca,
			String nazivBankeDuznika, String racunBankePoverioca,
			String racunBankeDuznika, double ukupno) {
		super();
		this.id = id;
		this.datumValute = datumValute;
		this.datum = datum;
		this.sifra = sifra;
		this.idRacunBankeDuznika = idRacunBankeDuznika;
		this.idRacunBankePoverioca = idRacunBankePoverioca;
		this.nazivBankePoverioca = nazivBankePoverioca;
		this.nazivBankeDuznika = nazivBankeDuznika;
		this.racunBankePoverioca = racunBankePoverioca;
		this.racunBankeDuznika = racunBankeDuznika;
		this.ukupno = ukupno;
	}

	/**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the datumValute property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumValute() {
        return datumValute;
    }

    /**
     * Sets the value of the datumValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumValute(XMLGregorianCalendar value) {
        this.datumValute = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }

    /**
     * Gets the value of the sifra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifra() {
        return sifra;
    }

    /**
     * Sets the value of the sifra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifra(String value) {
        this.sifra = value;
    }

    /**
     * Gets the value of the idRacunBankeDuznika property.
     * 
     */
    public int getIdRacunBankeDuznika() {
        return idRacunBankeDuznika;
    }

    /**
     * Sets the value of the idRacunBankeDuznika property.
     * 
     */
    public void setIdRacunBankeDuznika(int value) {
        this.idRacunBankeDuznika = value;
    }

    /**
     * Gets the value of the idRacunBankePoverioca property.
     * 
     */
    public int getIdRacunBankePoverioca() {
        return idRacunBankePoverioca;
    }

    /**
     * Sets the value of the idRacunBankePoverioca property.
     * 
     */
    public void setIdRacunBankePoverioca(int value) {
        this.idRacunBankePoverioca = value;
    }

    /**
     * Gets the value of the nazivBankePoverioca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivBankePoverioca() {
        return nazivBankePoverioca;
    }

    /**
     * Sets the value of the nazivBankePoverioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivBankePoverioca(String value) {
        this.nazivBankePoverioca = value;
    }

    /**
     * Gets the value of the nazivBankeDuznika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivBankeDuznika() {
        return nazivBankeDuznika;
    }

    /**
     * Sets the value of the nazivBankeDuznika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivBankeDuznika(String value) {
        this.nazivBankeDuznika = value;
    }

    /**
     * Gets the value of the racunBankePoverioca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRacunBankePoverioca() {
        return racunBankePoverioca;
    }

    /**
     * Sets the value of the racunBankePoverioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRacunBankePoverioca(String value) {
        this.racunBankePoverioca = value;
    }

    /**
     * Gets the value of the racunBankeDuznika property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRacunBankeDuznika() {
        return racunBankeDuznika;
    }

    /**
     * Sets the value of the racunBankeDuznika property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRacunBankeDuznika(String value) {
        this.racunBankeDuznika = value;
    }

    /**
     * Gets the value of the ukupno property.
     * 
     */
    public double getUkupno() {
        return ukupno;
    }

    /**
     * Sets the value of the ukupno property.
     * 
     */
    public void setUkupno(double value) {
        this.ukupno = value;
    }

}
